# Generated by Django 2.1.1 on 2018-09-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkit', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='bank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='route',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
