# Generated by Django 2.1.1 on 2018-09-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkit', '0003_auto_20180915_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
