# Generated by Django 2.1.1 on 2018-09-18 22:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkit', '0004_check_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=32, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', code='invalid_account_number', message='Only alphanumeric characters are allowed.')])),
                ('route', models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{9}$', code='invalid_routing_number', message='Routing number must be 9 digits.')])),
                ('address', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('wait_period', models.IntegerField(default=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='check',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='check',
            name='address',
        ),
        migrations.RemoveField(
            model_name='check',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='check',
            name='name',
        ),
        migrations.RemoveField(
            model_name='check',
            name='route',
        ),
        migrations.AddField(
            model_name='check',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='check',
            index=models.Index(fields=['date'], name='check_date_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='company_name_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['date'], name='account_date_idx'),
        ),
        migrations.AddField(
            model_name='check',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkit.Account'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checkit.Company'),
        ),
    ]
