# Generated by Django 2.1.1 on 2018-09-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkit', '0005_auto_20180918_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='to',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
