# Generated by Django 2.1.2 on 2018-10-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkit', '0008_auto_20181018_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
