# Generated by Django 2.1.2 on 2018-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkit', '0010_auto_20181018_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
