# Generated by Django 2.1.2 on 2018-10-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkit', '0012_auto_20181024_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, null=True),
        ),
    ]
