# Generated by Django 2.1.2 on 2018-11-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkit', '0013_auto_20181025_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
