# Generated by Django 2.1.2 on 2018-11-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkit', '0014_profile_is_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
