# Generated by Django 2.1.2 on 2018-11-28 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkit', '0015_auto_20181107_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='records_per_page',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
