# Generated by Django 2.1.2 on 2018-11-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkit', '0016_profile_records_per_page'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['route'], name='account_route_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['street'], name='account_street_idx'),
        ),
    ]
