# Generated by Django 2.1.2 on 2018-12-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkit', '0017_auto_20181130_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='paid_date',
            field=models.DateField(null=True),
        ),
    ]
